### ISSUE TITLE
Set up MGB heart failure data

### ISSUE THREAD

**Issue by payalchandak** [payalchandak/EveryQuery#12]

**Comment by mmcdermott** [comment]
Examples with run instructions and associated config files: https://github.com/mmcdermott/MEDS_transforms/tree/main/MIMIC-IV_Example
https://github.com/mmcdermott/MEDS_transforms/tree/main/AUMCdb_Example
https://github.com/mmcdermott/MEDS_transforms/tree/main/eICU_Example

**Comment by mmcdermott** [comment]
https://docs.google.com/presentation/d/1rFITOIEF7viXyYlui7Oqu950RZsyLMqiC0qYTNG8dDY/edit?usp=sharing

**Comment by payalchandak** [comment]
Run 
```
MEDS_transform-runner "pipeline_config_fp='/storage2/payal/EveryQuery/src/configs/extract_mgb.yaml'" stage_runner_fp='/storage2/payal/EveryQuery/src/configs/local_parallelism_runner.yaml'
```
